version: 2
jobs:
  build:
    working_directory: ~/workdir
    docker:
      - image: gradle:4.8-jdk8
    steps:
      - checkout
      - restore_cache:
          key: circleci-{{ checksum "build.gradle" }}
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: circleci-{{ checksum "build.gradle" }}
      - run: ./gradlew build
      - run: ./gradlew test


  docker-build:
      docker:
        - image: quay.io/klira/gradle-with-docker-client # (1)
      working_directory: ~/workdir
      steps:
        - checkout
        #- setup_remote_docker
        - run: chmod -v +x .circleci/*.sh
        - run: sh .circleci/docker-build.sh
        - persist_to_workspace:
            root: /tmp/workspace/
            paths:
              - jib-image.tar


  gcloud-deploy:
    docker:
      - image: google/cloud-sdk:167.0.0
        environment:
          PROJECT_NAME: zens-main
          CLUSTER_NAME: zens-kube
          CLOUDSDK_COMPUTE_ZONE: europe-west1-d
          DEBIAN_FRONTEND: noninteractive
    working_directory: ~/workdir
    steps:
      - checkout
      #- setup_remote_docker
      - deploy:
          name: Install Docker client
          command: |
            set -x
            VER="17.06.1-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - attach_workspace:
          at: /tmp/workspace
      - run: bash .circleci/gcloud-deploy.sh

  docker-deploy:
    docker:
      - image: docker:17.07.0   # (1)
    working_directory: ~/workdir
    steps:
      #- setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run:
        name: "Load saved image"
        command: |
          cd test
          docker load -i /tmp/workspace/jib-image.tar

      - deploy:
          command: |
            TAG=$CIRCLE_SHA1
            docker login -u $HUB_USERNAME -p $HUB_PASSWORD
            docker tag zensum/$ZENS_NAME:$CIRCLE_SHA1 zensum/$ZENS_NAME:latest
            docker push zensum/$ZENS_NAME:$TAG
            docker push zensum/$ZENS_NAME:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          context: org-global
      - docker-build:
          context: org-global
          requires:
            - build
          filters:
            branches:
              only: master
      - gcloud-deploy:
          context: org-global
          requires:
            - docker-build
            - build
          filters:
            branches:
              only: master
